apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: my_db
          imagePullPolicy: Never
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          ports:
            - containerPort: 3306
