apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: my_app
          imagePullPolicy: Never
          env:
            - name: DBHOST
              value: "mysql"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
            - name: DATABASE
              value: "employees"
            - name: APP_COLOR
              value: "blue"
          ports:
            - containerPort: 8080
