apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: my_db
    imagePullPolicy: Never
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "pw"
    ports:
      - containerPort: 3306
